name: Generate CycloneDX SBOM

on:
  push:
    branches:
      - master

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring

      - name: Install CycloneDX PHP Composer plugin
        composer require cyclonedx/cyclonedx-php-composer

      - name: Generate SBOM
        run: composer generate-sbom

      - name: Upload SBOM
        uses: actions/upload-artifact@v2
        with:
          name: sbom.xml
          path: ./sbom.xml

